.MODEL SMALL
.STACK 100H
.DATA
VALUE DB 11101010b ; BYTE TO COMPLIMENT CLEAR AND SET
CLEAR DB ?
SET DB ?
COMPLIMENT DB ?

.CODE

MAIN PROC
    MOV AX, @DATA
    MOV DS,AX
    
    
    ;PERFORMING SET OPERATION ON LSB
    MOV AL,VALUE
    OR AL,00000001b
    
    ;PERFORMING OR TO SET THE LSB FROM 0 TO 1!!
    
    ;PERFORMING CLEAR OPERATION ON MSB
    
    XOR AL,AL ; THIS WILL CLEAR THE PREVIOUS VALUE
    
    MOV AL,VALUE ; LOADING THE VALUE!!
    
    AND AL,01111111b
    
    ;PERFORMING AND OPERATION WILL CLEAR THE MSB
    
    ;PERFORMING COMPLEMENT OPERATION ON MSB
    
    XOR AL,AL ; CLEARING THE REGISTER
    
    MOV AL,VALUE
    
    XOR AL,10000000b ; PERFORMING THE COMPLEMENT!!!
    
    EXIT:
    
    MAIN ENDP

END MAIN